var SEC = 1e3;
var MIN = 60*SEC;

module.exports = {
  party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: {
    dunbar: 150,
    hops: 3
  },
  ws: {
    port: 8989
  },
  gossip: {
    connections: 3
  },
  path: '/.ssb',
  timers: {
    connection: 0,
    reconnect: 5*SEC,
    ping: 5*MIN,
    handshake: 5*SEC
  },
  //change these to make a test network that will not connect to the main network.
  caps: {
    //this is the key for accessing the ssb protocol.
    //this will be updated whenever breaking changes are made.
    //(see secret-handshake paper for a full explaination)
    //(generated by crypto.randomBytes(32).toString('base64'))
    shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',

    //used to sign messages
    sign: null
  },
  master: [],
  logging: { level: 'info' },
  party: true //disable quotas
};